name: Check Charm Revisions
on:
  workflow_dispatch

jobs:
  check-bundles:
    name: Check bundles for updates
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bundle_dir: [releases/sample1/edge/ca-scribner-test-bundle]
    steps:
      - uses: actions/checkout@v3
      # Get helpers
      - uses: actions/checkout@v3
        with:
          repository: ca-scribner/charm-ci-helpers
          path: _helpers
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: mv _helpers/*.py ./
      - name: Install Juju
        run: snap install juju --classic
      - run: tree
      - run: pip install -r _helpers/requirements.txt
      - run: python main.py ${{ matrix.bundle_dir }}/bundle.yaml ${{ matrix.bundle_dir }}/bundle.yaml
      - run: git status
