name: Check Charm Revisions
on:
  - workflow_dispatch
  - push  # For debugging only.  

jobs:
  check-bundles:
    name: Check bundles for updates
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bundle_dir: [releases/sample1/edge/ca-scribner-test-bundle]
    steps:
      - uses: actions/checkout@v3
      # Get helpers
      - uses: actions/checkout@v3
        with:
          repository: ca-scribner/charm-ci-helpers
          path: _helpers
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: mv _helpers/*.py ./
      - name: Install Juju
        run: sudo snap install juju --classic
      - run: tree
      - run: pip install -r _helpers/requirements.txt
      - run: python main.py ${{ matrix.bundle_dir }}/bundle.yaml ${{ matrix.bundle_dir }}/bundle.yaml
      - run: git status
      # We can make commits, but any untracked changes will still be committed by the action
      # - run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com>"
      #     git add -u
      #     git commit -m "Automated bump of charm revisions"
      
      # for some reason, this misses _helpers dir?  Either way, that's just temporary...
      - name: Clean up untracked changes
        run: git clean -fd
      # HACK
      - run: rm -rf _helpers
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
      # For debugging
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
