name: Check Charm Revisions
on:
  - workflow_dispatch
  - push  # For debugging only.  

jobs:
  get-release-matrix:
    name: Generate a Matrix of Releases in this Repo
    runs-on: ubuntu-latest
    outputs:
      release_paths_json: ${{ steps.get-release-matrix-step.outputs.PATHS_JSON }}
    steps:
      - uses: actions/checkout@v3
      - id: get-release-matrix-step
        run: |
          RELEASES=$(find releases -name bundle.yaml | xargs -L1 dirname | jq --slurp --raw-input 'split("\n")[:-1]' | jq -c "{\"release-path\": . }")
          echo "::set-output name=PATHS_JSON::$RELEASES"
  check-bundles:
    name: Check bundles for updates
    needs: get-release-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-release-matrix.outputs.release_paths_json) }}
    steps:
      - uses: actions/checkout@v3
      # Get helpers
      - uses: actions/checkout@v3
        with:
          repository: ca-scribner/charm-ci-helpers
          path: _helpers
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: mv _helpers/*.py ./
      - name: Install Juju
        run: sudo snap install juju --classic
      - run: tree
      - run: pip install -r _helpers/requirements.txt
      - run: python main.py ${{ matrix.release-path }}/bundle.yaml ${{ matrix.release-path }}/bundle.yaml
      - run: git status
      # We can make commits, but any untracked changes will still be committed by the action
      # - run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com>"
      #     git add -u
      #     git commit -m "Automated bump of charm revisions"
      
      # for some reason, this misses _helpers dir?  Either way, that's just temporary...
      - name: Clean up untracked changes
        run: git clean -fd
      # HACK
      - run: rm -rf _helpers
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          # TODO: Sanitize this so it is always an ok branch name
          branch: ${{ matrix.release-path }}
          title: (automated) Outdated charms detected in Release ${{ matrix.release-path }}
          body: This is an automated PR to bump all outdated charms to their most recent version.  
      # For debugging
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
